### ISSUE TITLE
Memoizing Beamer frames

### ISSUE THREAD

**Issue by amonakov** [sasozivanovic/memoize#5] opened 2023-12-29 09:54 UTC
Beamer frames appear to be a tempting target for memoization, but

- a mysterious error is produced without `capture=vbox`
- with `capture=vbox` an empty frame appears before a memoized frame, with the following appearing in the log:
```
Underfull \vbox (badness 10000) has occurred while \output is active []
Overfull \vbox (13.6pt too high) has occurred while \output is active []
```

Here's what I tried:
```latex
\RequirePackage[record=makefile,extract=no,auto={frame}{memoize,capture=vbox}]{memoize}
\documentclass{beamer}
\begin{document}
\begin{frame}
\end{frame}
\end{document}
```
What do you think, is it a worthwhile idea? Thank you!

**Comment by sasozivanovic** [comment] 2023-12-29 10:22
It is most definitely a worthwhile idea, but I'm afraid memoizing Beamer frames is impossible from within Memoize. As far as I see, this could only be done from the Beamer's side. Perhaps you could ask the Beamer developers if they are willing to implement support? I'd be happy to help, of course.

To see why Memoize can't possibly memoize frames on its own, remember that a `frame` environment can produce several pages (overlays).

**Comment by amonakov** [comment] 2023-12-30 08:48
Thank you for the swift response! Looking under the hood, I found internal `beamer@frameslide` environment and came up with this snippet:
```latex
\makeatletter
\mmzset{auto={beamer@frameslide}{memoize,capture=vbox,per overlay}}
\makeatother
```
It has the following issues:

- does not support fragile slides
- a frame following a pause is dropped on recompilation

Can you have a look at the latter issue? It seems related to handling of pauses described in section 4.2.4 of the documentation. Here's my MWE:

```latex
\RequirePackage[record=makefile,extract=no]{memoize}
\documentclass{beamer}
\begin{document}
\makeatletter
\mmzset{auto={beamer@frameslide}{memoize,capture=vbox,per overlay}}
\makeatother
\begin{frame}
  Hello,\pause{} World!
\end{frame}
\end{document}
```

**Comment by sasozivanovic** [comment] 2023-12-30 21:19
I will look into this, but it might take a while.

**Comment by cfr42** [comment] 2024-04-18 00:08
The externs are created, but the problem is the same as for Beamer slides without `per overlay`: there's nothing in the c-memo to tell Beamer to make the second slide when including the externs on subsequent runs. Something about pauses needs to get into the main memo. I tried faking it by feeding the value of `beamerpauses` to `\mmzSetBeamerOverlays`, but I don't understand how to append the material correctly; no matter what I try, I end up with `\mmzSetBeamerOverlays {1}{2}\mmzSetBeamerOverlays {1}{0}` rather than the other way around, as I'd naïvely expect. (The definitions get done in the right order, but they end up backwards when added to `\mmzCMemo` and I don't know why.)

**Comment by sasozivanovic** [comment] 2024-10-19 18:10
I'm closing this issue even though it has not really been resolved, because I put the following feature on my TODO list — even if not on the very top ...

* Investigate whether it is possible to memoize whole pages, i.e. instead of duplicating a box as an extern page, mark the pages shipped out during memoization as externs.

Without this functionality, memoizing Beamer frames is imho impossible. With this functionality, it might just work, even if I'm not sure whether we can expect perfection.  Another possible application is externalization of entire chapters (#30).

**Closed by sasozivanovic** 2024-10-19 18:10 UTC
